project:
  type: website
  output-dir: docs

website:
<<<<<<< Updated upstream
  title: "FISTIKCI SAHAP"
=======
  title: "XX TakD1mD1 Analitik LabD1"
>>>>>>> Stashed changes
  navbar:
    search: true
    left:
      - text: Ana Sayfa
        href: index.qmd
      - text: TakD1m Cyeleri
        href: takim.qmd
      - text: Porfolyo
        href: portfolyo.qmd
      - text: Proje
        href: proje.qmd


            
    tools:
       icon: github
       href: https://github.com

  sidebar:
    - title: "CalD1Emalar"
      style: "docked"
      search: true
      contents:
        - portfolyo.qmd
        - portfolyo/calisma1.qmd
        - portfolyo/calisma2.qmd  
        
    - title: "TakD1m"
      style: "docked"
      search: true
      contents:
        - takim.qmd
<<<<<<< Updated upstream
        - takim/esen.qmd
        - takim/cansu.qmd
        - takim/yesim.qmd  
=======
        - takim/dusantadic.qmd
        - takim/edindzeko.qmd
        - takim/fred.qmd  
>>>>>>> Stashed changes
        - takim/ugur.qmd  
        
        
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "EMU Hacettepe MUY665 - 2024-2025 Bahar" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: simplex 
      dark: cyborg
    css: styles.css


editor: visual

