---
title: "Proje X (proje adını yazınız)"
number-sections: true
---

**Proje sayfamıza hoş geldiniz.**

*Projemizle ilgili güncellemelerden haberdar olmak için bu alanı takip edin.*

(Aşağıdaki başlıklar örnek olarak verilmiştir; lütfen gerektiği şekilde düzenlemekten çekinmeyin.)

# Proje Genel Bakış ve Kapsamı

Bu proje, Türkiye'deki ikinci el araç piyasasına dair verilerin analiz edilmesini amaçlayan bir çalışmadır. Verilen araç satış verileri üzerinden çeşitli analizler yaparak, fiyatların nasıl dağıldığını, araçların farklı özelliklerinin fiyat üzerindeki etkilerini, piyasa trendlerini ve diğer önemli faktörleri incelemeyi hedeflemektedir.

# Veri

```{r}
 data <- read.csv("/Users/kullanıcıadı/Desktop/turkey_car_market.csv", header = TRUE, sep = ",")

 install.packages("dplyr")
 library(dplyr)

 result <- data %>%
+   group_by(Marka, Arac.Tip.Grubu) %>%
+   summarise(Max_Price = max(Fiyat, na.rm = TRUE)) %>%
+   group_by(Marka) %>%
+   filter(Max_Price == max(Max_Price)) %>%
+   arrange(desc(Max_Price))

```

## Veri Kaynağı

xxxxxx

## Veri Hakkında Genel Bilgiler

xxxxxx

## Tercih Sebebi

xxxxxx

## Ön İşleme

xxxxxx

# Analiz

xxxxxx

## Keşifsel Veri Analizi

xxxxxx

## Trend Analizi

xxxxxx

## Model Uydurma

xxxxxx

## Sonuçlar

xxxxxx

# Sonuçlar ve Ana Çıkarımlar

xxxxxx
